# ----
# Site

title: Brian Dombrowski
url: "https://briandombrowski.info"

# Values for the jekyll-seo-tag gem (https://github.com/jekyll/jekyll-seo-tag)
logo: /siteicon.png
description: A quick get to know me.
author:
  name: Benevolent Tech
  email: brian@benevolent.tech
  twitter: benevolentweb
social:
  name: Benevolent Tech
  links:
    - https://benevolent.tech

# -----
# Build

gems:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-archives
  - jekyll_image_encode
  - jekyll-sitemap
  - jekyll-mentions
  - jekyll-paginate
  - algoliasearch-jekyll

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENCE
  - node_modules
  - gulpfile.js
  - css/_src
  - js/_src

collections:
  staff_members:
    _hide_content: true

jekyll-mentions:
  base_url: https://twitter.com


defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
  -
    scope:
      type: "posts"
    values:
      layout: "post"
  -
    scope:
      path: "contact-success.html"
    values:
      layout: "page"
