# ----
# Site

title: DC Facades
url: "https://dcfacades.com"
baseurl:
google_analytics_key:
google_maps_javascript_api_key: AIzaSyDj-bVK8EaDmKmAAtNIuo1fvWLDTbLuLI0
fb_app_id:
disqus_shortname:

# Values for the jekyll-seo-tag gem (https://github.com/jekyll/jekyll-seo-tag)
logo: /siteicon.png
description: Signs and Storefront Improvement Services
author:
  name: Brian Dombrowski
  email: brian@benevolent.tech
  twitter: benevolentweb
social:
  name: DC Facades
  links:
    - https://benevolent.tech

# -----
# Build

permalink: /blog/:title.html

gems:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-archives

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENCE
  - node_modules

collections:
  staff_members:
    _hide_content: true

paginate: 10
paginate_path: "/blog/:num/"

jekyll-archives:
  enabled: ['categories']

defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
  -
    scope:
      type: "posts"
    values:
      layout: "post"
  -
    scope:
      path: "contact-success.html"
    values:
      layout: "page"

# -----------
# CloudCannon

social_icons:
  - Facebook
  - Google Plus
  - Instagram
  - LinkedIn
  - Pinterest
  - Tumblr
  - Twitter
  - YouTube
  - Email
  - RSS

_comments:
  description: Signs and Storefront Improvement Services
  blurb: Signs and Storefront Improvement Services
