# ----
# Site

title: DC Facades
url: "https://dcfacades.com"

# Values for the jekyll-seo-tag gem (https://github.com/jekyll/jekyll-seo-tag)
logo: /siteicon.png
description: Signs and Storefront Improvement Services
author:
  name: Benevolent Tech
  email: brian@benevolent.tech
  twitter: benevolentweb
social:
  name: DC Facades
  links:
    - https://benevolent.tech

# -----
# Build

permalink: /blog/:title.html

gems:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-archives
  - jekyll_image_encode
  - jekyll-sitemap
  - jekyll-mentions
  # - algoliasearch-jekyll

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENCE
  - node_modules
  - gulpfile.js
  - css/_src
  - js/_src

collections:
  staff_members:
    _hide_content: true

jekyll-mentions:
  base_url: https://twitter.com

paginate: 5
paginate_path: "/blog/:num/"

jekyll-archives:
  enabled: ['categories']

defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
  -
    scope:
      type: "posts"
    values:
      layout: "post"
  -
    scope:
      path: "contact-success.html"
    values:
      layout: "page"

_comments:
  description: Signs and Storefront Improvement Services
  blurb: Signs and Storefront Improvement Services

#algolia:
#  application_id: 'MUZJLD13O2'
#  index_name:     'Benevolent Tech Main'
#  record_css_selector: 'p,ul,ol,h1,h2,h3,h4,h5'
#  settings:
#      attributesToIndex:
#        - title
#        - h1
#        - h2
#        - h3
#        - h4
#        - h5
#        - h6
#        - unordered(text)
#        - unordered(tags)
#        - ul
#        - ol
#  excluded_files:
#      - seo-starter-spreadsheet-success.html
#      - newsletter-success.html