# ----
# Site

title: Master Prototype
url: "https://benevolent.tech"

# Values for the jekyll-seo-tag gem (https://github.com/jekyll/jekyll-seo-tag)
logo: /siteicon.png
description: This is the site description
author:
  name: Benevolent Tech
  email: brian@benevolent.tech
  twitter: benevolentweb
social:
  name: Benevolent Tech
  links:
    - https://benevolent.tech

# -----
# Build

permalink: /post/:title.html

gems:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-archives
  - jekyll_image_encode
  - jekyll-sitemap
  - jekyll-paginate
  # - algoliasearch-jekyll # depends on nokogiri. Never push this gem installed to production.

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENCE
  - node_modules
  - gulpfile.js
  - css/_src
  - js/_src

collections:
  staff_members:
    _hide_content: true

jekyll-mentions:
  base_url: https://twitter.com

paginate: 3
paginate_path: "/blog/:num/"

jekyll-archives:
  enabled: ['categories']

defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
  -
    scope:
      type: "posts"
    values:
      layout: "post"
  -
    scope:
      path: "contact-success.html"
    values:
      layout: "page"

_comments:
  description: This is the comment description
  blurb: This is the site description

algolia:
  application_id: 'MXFG5KRPB4'
  searchonly_api_key: '915e9c731ef75764d72b6f4da44ada7d'
  index_name:     'Main'
  record_css_selector: 'p,ul,ol,h1,h2,h3,h4,h5'
  settings:
      attributesToIndex:
        - title
        - h1
        - h2
        - h3
        - h4
        - h5
        - h6
        - unordered(text)
        - unordered(tags)
        - ul
        - ol
  excluded_files:
      - blog
      - blog/*
      - search.html
      - contact-success.html